sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
  - sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev libwebp-dev
  - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
  - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
  - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm
language: python
python:
- "3.5"
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database sample22;' -U postgres

env:
- DATABASE_URL=postgres://postgres:postgres@127.0.0.1/sample22

install: pip install -r requirements/local.txt
script: python manage.py test -k
