# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 19:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import tuteria_application_test.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('g_objects', tuteria_application_test.users.models.CustomUserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='not_started', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.Wallet'),
        ),
    ]
