# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-13 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170512_2335'),
        ('users', '0003_auto_20170429_2000'),
    ]

    operations = [
    ]
