# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-24 20:57
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170624_1419'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('g_objects', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Completed', 'completed'), ('Cancelled', 'cancelled'), ('Scheduled', 'scheduled'), ('Not Started', 'not_started')], default='not_started', max_length=12),
        ),
    ]
