# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170605_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='not_started', max_length=12),
        ),
    ]
